### ISSUE TITLE
Bot stuck on "Chat-GPT is thinking"

### ISSUE THREAD

**Issue by a3312a** [TheExplainthis/ChatGPT-Discord-Bot#11]
I get this error 
 [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\SGB2\main.py", line 33, in chat
    receive = chatgpt.get_response(user_id, message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Downloads\\src\chatgpt.py", line 12, in get_response
    response = self.model.chat_completion(self.memory.get(user_id))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Downloads\\src\models.py", line 20, in chat_completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'ChatCompletion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'chat' raised an exception: AttributeError: module 'openai' has no attribute 'ChatCompletion'

**Comment by asudox** [comment]
This is because the object `openai` does not have a attribute named `ChatCompletion`.
